apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omnigent

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
